### ISSUE TITLE
python binding: OSError libggml.so: cannot open shared object file

### ISSUE THREAD

**Issue by Yossef-Dawoad** [monatis/clip.cpp#55] opened 2023-09-12 19:15 UTC
Hello, first super thanks for your awesome work in the `clip.cpp`,
I encountered an error wile experimenting with your python binding.
installing `clip_cpp` python binding with:
```bash
 pip install clip_cpp
```
while the install is successful importing the `Clip` model through this
```python 
from clip_cpp import Clip
```
result in this error, which it cannot link the `libggml.so`
```bash
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-3-3550bf91251e>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from clip_cpp import Clip

2 frames
[/usr/lib/python3.10/ctypes/__init__.py](https://localhost:8080/#) in __init__(self, name, mode, handle, use_errno, use_last_error, winmode)
    372 
    373         if handle is None:
--> 374             self._handle = _dlopen(self._name, mode)
    375         else:
    376             self._handle = handle

OSError: libggml.so: cannot open shared object file: No such file or directory
```

**Comment by monatis** [comment] 2023-09-12 23:00
Weird, it shouldn't even try to load libggml.so. What is your OS, CPU architecture etc.? It might be due to the ggml is built with `-march=native` maybe, because it works on my machine when I install it from Pip. I'll try to reproduce with your OS / CPU features.

**Comment by Yossef-Dawoad** [comment] 2023-09-12 23:57
I tried to experiment with it in google colab that when I get this error which led me to build it from the source to test it more and i get it to work inside the `examples/python_bindings/` folder here is my colab link [here](https://colab.research.google.com/drive/1arpQwOsWOpQoBBdcp1lXCOmak3vdjDhX?usp=sharing) maybe i did something wrong 
> I ran the import on my windows after pip install it and get different osError `OSError: [WinError 193] %1 is not a valid Win32 application`

**Comment by monatis** [comment] 2023-09-13 08:36
This should be fixed with the latest release on Pip. 
 
```sh
pip install --upgrade clip-cpp
```

> I ran the import on my windows after pip install it and get different osError OSError: [WinError 193] %1 is not a valid Win32 application

Unfortunately, Windows is not supported from Pip for now. The package installed from Pip supports only X64 Linux distros (like Colab), and it can be built from source on other platforms.

I'm thinking of further improving the Python binding, and so Windows support for Pip-install is on the desk.

**Comment by denis-ismailaj** [comment] 2023-09-13 08:51
Can confirm the latest release fixes this.

On a clean python:3.11 docker image:

    pip install 'clip_cpp==0.3.2'
    python -c 'from clip_cpp import Clip'

> OSError: libggml.so: cannot open shared object file: No such file or directory

    pip install -U clip_cpp
    python -c 'from clip_cpp import Clip'
    echo $?
> 0

**Closed by denis-ismailaj** 2023-09-13 08:51 UTC
